# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c17a3befe08d12f9fabc5b0159b9fd58be4bc512c45547b82a6d6814eaa71e82656748397bd20743486a02800b3dfc90c1f68ebc396cf1cc47bd7ca861d3474a

test:
  secret_key_base: 767c0e27412fff807dfa2cedb0b4c5af41fd0548222ad230c3f6fa91b4d5ce7316dc5bd23dc7c83b44b9c09686883a16527466bac864c66cd12db847339e41a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
